### PR TITLE
BUGFIX: Implode multidimensional propertyValues to string

### PR DESCRIPTION
**Pull request by gerdemann**

### CODE REVIEW

**Comment by kitsunet** [comment]
Isn't that exaclty what implode does?

**Comment by kitsunet** [comment]
oh wait, multi-dimensional, yeah I get it, but in that case... Mmmm, not rather just json_encode?

**Comment by gerdemann** [comment]
@kitsunet Changed it to json_encode

**Comment by kitsunet** [comment]
Clsoing, fixed with #26 26

**Pull request closed without merging**
