### PR TITLE
FEATURE: MySQL indexing

### PR DESCRIPTION
**Pull request by kdambekalns**
This provides indexing based on `FULLTEXT` indexes in MySQL.

### CODE REVIEW

**Comment by kdambekalns** [comment]
This should become 3.0 – if you like I can provide a PR for 2.0 to add compatibility with Flow 6 without breaking changes.

**Comment by daniellienert** [comment]
@kitsunet I tried to test the implementation. On a fresh installation, I only get the page-titles indexed. No Content, even when configured like 

```
'Neos.Demo:Content.Text':
  properties:
    'text':
      search:
        fulltextExtractor: '${Indexing.extractHtmlTags(value)}'
```

did that work for you?

**Comment by kitsunet** [comment]
mmm, let me re-check that!

**Comment by kitsunet** [comment]
Nope, works fine, are you sure you configured fulltext indexing for the nodetype?
```
'Neos.Demo:Content.Text':
  properties:
    'text':
      search:
        fulltextExtractor: '${Indexing.extractHtmlTags(value)}'
  search:
    fulltext:
      enable: true
```

This works fine for me, note thoug that probably Text doesn'T even contain headlines, so try that config also for the headline component.

**Pull request merged**
